### ISSUE TITLE
Convert into CLI app

### ISSUE THREAD

**Issue by sandaemc** [CodingAvenue/ca-school-summary-parser#2]
Platform and reader is currently using this. Platform is written in PHP so it's using the reader's expose endpoint to grab the TOC result. We need to make this npm bin executable so Platform can call directly.

 - [x] Convert to cli
 - [x] Publish to npmjs.com
 - When done,
   - [x] Create a ticket in reader to update its usage - assign to sandae
   - [x] Create a ticket in platform to update its usage - assign to @rosoarv

**Comment by sandaemc** [comment]
@mmacaso @rosoarv fyi

**Comment by rosoarv** [comment]
@sandaemc ok. noted!

**Comment by TenshiLyle** [comment]
https://www.npmjs.com/package/summary-parser
